version: 2.1

jobs:
  docker-build:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout

      - setup_remote_docker

      # Restore Yarn cache
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines

      # Save Yarn cache
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}

      # Run tests
      - run:
          name: Run Tests
          command: CI=true yarn test

      # Build React app
      - run:
          name: Build App
          command: yarn build

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t culture-connect .

workflows:
  build-and-test:
    jobs:
      - docker-build