version: 2.1

jobs:
  build-test-docker:
    docker:
      - image: cimg/node:20.5

    steps:
      - checkout

      # Enable Docker
      - setup_remote_docker

      # Restore Yarn cache
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines

      # Save cache
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}

      # Run tests
      - run:
          name: Run Tests
          command: CI=true yarn test

      # Build React App
      - run:
          name: Build React App
          command: yarn build

      # Build Docker Image
      - run:
          name: Build Docker Image
          command: docker build -t culture-connect .

      # Login to Docker Hub
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Tag Docker Image
      - run:
          name: Tag Docker Image
          command: docker tag culture-connect $DOCKER_USERNAME/culture-connect:latest

      # Push Docker Image
      - run:
          name: Push Docker Image
          command: docker push $DOCKER_USERNAME/culture-connect:latest

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-docker